name : Golang web example
on: 
    push:
        branches:
        - 'v1.2'
        tags:
        - 'latest'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
